# Sensores
DHT_PIN = 14
SOIL_POWER_PIN = 25
SOIL_ANALOG_PIN = 34
LDR_ANALOG_PIN = 35

WIFI_SSID = ""
WIFI_PASSWORD = ""

# API
API_URL = "<SEU IP>:8000/api/leituras"
DEVICE_ID = "esp32-estufa-01"
READ_INTERVAL_SECONDS = 10